FROM adoptopenjdk/openjdk11:latest
COPY ./target/team_management-0.0.1-SNAPSHOT.jar /usr/app/
WORKDIR /usr/app
RUN sh -c "touch team_management-0.0.1-SNAPSHOT.jar"
ENTRYPOINT ["java","-jar","team_management-0.0.1-SNAPSHOT.jar"]
EXPOSE 8080